"use client";
import { useState } from "react";
type View = "home" | "services" | "about" | "contact";
const themes = [
  { id: "signal", label: "01 Signal", note: "Research lab" },
  { id: "atlas", label: "02 Atlas", note: "Enterprise" },
  { id: "terminal", label: "03 Terminal", note: "Technical" },
  { id: "field", label: "04 Field Notes", note: "Editorial" },
  { id: "prism", label: "05 Prism", note: "Agentic" },
] as const;
const services = [
  { n: "01", title: "Agentic systems", body: "Design and production engineering for reliable multi-agent workflows, tool use, orchestration, memory, and human oversight." },
  { n: "02", title: "AI security", body: "Threat modeling, adversarial testing, red teaming, control design, and practical defenses for systems that can reason and act." },
  { n: "03", title: "Evals & assurance", body: "Evaluation architecture, curated datasets, judges, failure taxonomies, and continuous improvement loops tied to business risk." },
  { n: "04", title: "Technical strategy", body: "Architecture, platform direction, build-vs-buy decisions, team enablement, and a grounded path from prototype to production." },
];
const proof = ["Agent architecture", "AI security research", "Evaluation systems", "Product engineering"];
function Mark() { return <span className="mark" aria-hidden="true"><i>1</i><i>7</i></span>; }
export default function Home() {
  const [theme, setTheme] = useState<(typeof themes)[number]["id"]>("signal");
  const [view, setView] = useState<View>("home");
  return <main className={`site theme-${theme}`}>
    <aside className="concept-bar" aria-label="Website concepts"><span className="concept-title">Choose a direction</span><div className="concept-options">{themes.map(item => <button key={item.id} className={theme === item.id ? "active" : ""} onClick={() => setTheme(item.id)}><span>{item.label}</span><small>{item.note}</small></button>)}</div></aside>
    <div className="shell">
      <header><button className="brand" onClick={() => setView("home")} aria-label="17th Street Labs home"><Mark/><span>17th Street Labs</span></button><nav aria-label="Main navigation">{(["home","services","about","contact"] as View[]).map(item => <button key={item} className={view === item ? "current" : ""} onClick={() => setView(item)}>{item}</button>)}</nav><button className="nav-cta" onClick={() => setView("contact")}>Start a conversation <span>↗</span></button></header>
      {view === "home" && <HomeView onNavigate={setView}/>} {view === "services" && <ServicesView onNavigate={setView}/>} {view === "about" && <AboutView onNavigate={setView}/>} {view === "contact" && <ContactView/>}
      <footer><div className="footer-brand"><Mark/><span>17th Street Labs</span></div><p>AI systems that deserve to be trusted.</p><span>© 2026 · Denver / Everywhere</span></footer>
    </div>
  </main>;
}
function HomeView({onNavigate}:{onNavigate:(v:View)=>void}) { return <><section className="hero"><div className="eyebrow"><span/> Agentic AI · Security · Assurance</div><h1>We build AI systems<br/>that can <em>earn trust.</em></h1><p>17th Street Labs helps ambitious teams design, secure, evaluate, and ship agentic software that works beyond the demo.</p><div className="hero-actions"><button className="primary" onClick={()=>onNavigate("contact")}>Work with us <span>↗</span></button><button className="secondary" onClick={()=>onNavigate("services")}>Explore our work <span>→</span></button></div><div className="hero-art" aria-hidden="true"><span className="orb core"/><span className="orb a"/><span className="orb b"/><span className="orb c"/><i/><i/><i/></div></section><section className="proof-strip">{proof.map((p,i)=><div key={p}><b>0{i+1}</b><span>{p}</span></div>)}</section><section className="manifesto"><span className="kicker">The premise</span><h2>Agency changes the risk model.</h2><p>Software that can plan, choose tools, and act on a user’s behalf requires more than a better prompt. We bring engineering discipline, adversarial thinking, and measurable assurance to every layer.</p></section></>; }
function ServicesView({onNavigate}:{onNavigate:(v:View)=>void}) { return <><section className="page-head"><div className="eyebrow"><span/> Services</div><h1>From uncertain prototype<br/>to <em>trusted system.</em></h1><p>Focused engagements for teams building at the edge of what AI can do.</p></section><section className="service-grid">{services.map(s=><article key={s.n}><b>{s.n}</b><h2>{s.title}</h2><p>{s.body}</p><span className="arrow">↗</span></article>)}</section><section className="process"><span className="kicker">How we engage</span><div><b>Discover</b><i/><b>Design</b><i/><b>Prove</b><i/><b>Transfer</b></div><p>Small senior teams, explicit success criteria, rapid evidence, and capability that stays with your organization.</p><button className="primary" onClick={()=>onNavigate("contact")}>Discuss an engagement ↗</button></section></>; }
function AboutView({onNavigate}:{onNavigate:(v:View)=>void}) { return <><section className="page-head"><div className="eyebrow"><span/> About the lab</div><h1>Senior judgment for<br/><em>new kinds of systems.</em></h1><p>We combine decades of software engineering and organizational leadership with hands-on AI research and product work.</p></section><section className="principles"><span className="kicker">What we believe</span><div><article><b>01</b><h2>Evidence over theater</h2><p>Good demos inspire. Good evaluations tell you whether the system is ready.</p></article><article><b>02</b><h2>Security is architecture</h2><p>It belongs in agent boundaries, permissions, data flows, and operating models from day one.</p></article><article><b>03</b><h2>Capability should transfer</h2><p>Consulting succeeds when your team becomes stronger and more independent.</p></article></div></section><section className="people"><span className="kicker">Principals</span><div className="people-grid"><article><div className="portrait">DL</div><div><h2>Dan Levy</h2><b>Engineering · AI systems · Security</b><p>Engineer, educator, and technical leader focused on agentic architectures, evaluation systems, AI security, and high-leverage engineering organizations.</p><a href="mailto:dan@17thstreetlabs.com">dan@17thstreetlabs.com *</a></div></article><article><div className="portrait">M</div><div><h2>Marina</h2><b>Strategy · Operations · Client partnerships</b><p>Helping translate ambitious ideas into clear engagements, durable partnerships, and work that creates measurable value.</p><a href="mailto:marina@17thstreetlabs.com">marina@17thstreetlabs.com *</a></div></article></div><small>* Placeholder contact details. Replace before launch.</small><button className="secondary" onClick={()=>onNavigate("contact")}>Contact the team →</button></section></>; }
function ContactView() { return <section className="contact-page"><div className="contact-copy"><div className="eyebrow"><span/> Contact</div><h1>Bring us the<br/><em>hard problem.</em></h1><p>Tell us what you’re building, what’s at risk, and where uncertainty is slowing you down.</p><div className="direct"><span>General inquiries</span><a href="mailto:hello@17thstreetlabs.com">hello@17thstreetlabs.com *</a><span>Dan Levy</span><a href="mailto:dan@17thstreetlabs.com">dan@17thstreetlabs.com *</a><span>Marina</span><a href="mailto:marina@17thstreetlabs.com">marina@17thstreetlabs.com *</a><small>* Placeholder email addresses</small></div></div><form className="contact-form" onSubmit={e=>e.preventDefault()}><label>Name<input placeholder="Your name"/></label><label>Work email<input type="email" placeholder="you@company.com"/></label><label>What can we help with?<select defaultValue=""><option value="" disabled>Select a focus</option><option>Agentic systems</option><option>AI security</option><option>Evals & assurance</option><option>Technical strategy</option></select></label><label>Tell us a little more<textarea placeholder="What are you building?" rows={5}/></label><button className="primary" type="submit">Send inquiry ↗</button><small>Demo form only. Connect your preferred form service before launch.</small></form></section>; }
